/** Public surface of the channel declaration shared by the main process and the renderer. */

export { CHANNELS, windowCommandSchema } from './channels.ts'
export type {
  Bridge,
  ChannelArguments,
  ChannelName,
  ChannelResponse,
  Channels,
} from './channels.ts'
export {
  displaySchema,
  environmentReportSchema,
  graphicsSchema,
  motionMeasureSchema,
  versionsSchema,
} from './environment.ts'
export type {
  Display,
  EnvironmentReport,
  Graphics,
  MotionMeasure,
  Versions,
} from './environment.ts'
export {
  DEFAULT_DISPLAY_PREFERENCES,
  ENGINE_EVENTS,
  ENGINE_EVENT_CHANNEL,
  ENGINE_REQUESTS,
  channelSchema,
  composerChoiceSchema,
  composersSchema,
  displayPreferencesChangeSchema,
  activeProjectSchema,
  activeSessionsSchema,
  displayPreferencesSchema,
  engineStatusSchema,
  entityKindSchema,
  eventAuthorSchema,
  eventSourceSchema,
  journalEntrySchema,
  projectSchema,
  projectToneSchema,
  repositoryIconSchema,
  sessionEntryOriginSchema,
  sessionEntrySchema,
  sessionSchema,
  sessionTitleSourceSchema,
  sidebarPreferenceSchema,
  themePreferenceSchema,
} from './engine.ts'
export type {
  Channel,
  RepositoryIcon,
  ComposerChoice,
  DisplayPreferences,
  DisplayPreferencesChange,
  EngineArguments,
  EngineEvent,
  EngineEventName,
  EngineRequestName,
  EngineRequests,
  EngineResponse,
  EngineStatus,
  SidebarPreference,
  ThemePreference,
  JournalEntry,
  Project,
  Session,
  SessionEntry,
  SessionEntryOrigin,
  SessionTitleSource,
} from './engine.ts'
export {
  agentAvailabilitySchema,
  agentOfferRefusalSchema,
  agentOfferSchema,
  agentProviderSchema,
  agentUpdateSchema,
  bareModeSchema,
  configOptionSchema,
  installerToolSchema,
  resumeStateSchema,
  stopReasonSchema,
  toolCallStatusSchema,
} from './agents.ts'
export type {
  AgentAvailability,
  AgentOffer,
  AgentOfferRefusal,
  AgentProvider,
  AgentUpdate,
  BareModeState,
  ConfigOption,
  InstallerTool,
  ResumeState,
  StopReason,
  ToolCallStatus,
} from './agents.ts'
export {
  commandRunSchema,
  commandSchema,
  commandScopeSchema,
  commandTypeSchema,
  contextReachSchema,
  contextViewSchema,
  providedSchema,
  runStateSchema,
} from './tools.ts'
export type {
  Command,
  CommandRun,
  CommandScope,
  CommandType,
  ContextView,
  Provided,
  RunState,
} from './tools.ts'
export {
  recipeKindSchema,
  recipeStepSchema,
  repositoryStateSchema,
  variableSchema,
  workspacePlanSchema,
  workspaceSchema,
  workspaceStateSchema,
  workspaceStepSchema,
  worktreeSchema,
} from './workspaces.ts'
export type {
  RecipeStep,
  RepositoryState,
  Variable,
  Workspace,
  WorkspacePlan,
  WorkspaceState,
  WorkspaceStep,
  Worktree,
} from './workspaces.ts'
export {
  SPEC_REQUESTS,
  acceptanceCriterionSchema,
  editBufferSchema,
  missionSchema,
  phaseIdSchema,
  phaseStateSchema,
  sectionNameSchema,
  specActorSchema,
  specAnswerSchema,
  specPhaseSchema,
  specQuestionOptionSchema,
  specQuestionSchema,
  specRevisionSchema,
  specSchema,
  specSectionSchema,
  specSnapshotSchema,
  specStatusSchema,
  specSummarySchema,
  specTaskSchema,
  specTypeSchema,
  taskDependencySchema,
  taskExecutorSchema,
  taskSetSchema,
  taskStorySchema,
  userStorySchema,
} from './specs.ts'
export type {
  AcceptanceCriterion,
  EditBuffer,
  Mission,
  PhaseId,
  PhaseState,
  SectionName,
  Spec,
  SpecActor,
  SpecAnswer,
  SpecPhase,
  SpecQuestion,
  SpecQuestionOption,
  SpecRevision,
  SpecSection,
  SpecSnapshot,
  SpecStatus,
  SpecSummary,
  SpecTask,
  SpecType,
  TaskDependency,
  TaskExecutor,
  TaskSet,
  TaskStory,
  UserStory,
} from './specs.ts'
export {
  BUILD_REQUESTS,
  attemptFileSchema,
  attemptResultSchema,
  attemptScopeSchema,
  attemptViewSchema,
  blockerViewSchema,
  buildPhaseSchema,
  buildTaskStateSchema,
  buildTaskViewSchema,
  buildViewSchema,
  checkDraftSchema,
  checkResultViewSchema,
  checkVerdictSchema,
  checkWhenSchema,
  checkWhereSchema,
  projectCheckSchema,
  storyViewSchema,
} from './build.ts'
export type {
  AttemptView,
  BlockerView,
  BuildPhase,
  BuildTaskState,
  BuildTaskView,
  BuildView,
  CheckDraft,
  CheckResultView,
  ProjectCheck,
  StoryView,
} from './build.ts'
