/** Public surface of the channel declaration shared by the main process and the renderer. */

export { CHANNELS, windowCommandSchema } from './channels.ts'
export type {
  Bridge,
  ChannelArguments,
  ChannelName,
  ChannelResponse,
  Channels,
} from './channels.ts'
export {
  displaySchema,
  environmentReportSchema,
  graphicsSchema,
  motionMeasureSchema,
  versionsSchema,
} from './environment.ts'
export type {
  Display,
  EnvironmentReport,
  Graphics,
  MotionMeasure,
  Versions,
} from './environment.ts'
export {
  DEFAULT_DISPLAY_PREFERENCES,
  ENGINE_EVENTS,
  ENGINE_EVENT_CHANNEL,
  ENGINE_REQUESTS,
  channelSchema,
  composerChoiceSchema,
  composersSchema,
  displayPreferencesChangeSchema,
  activeProjectSchema,
  activeSessionsSchema,
  displayPreferencesSchema,
  engineStatusSchema,
  entityKindSchema,
  eventAuthorSchema,
  eventSourceSchema,
  journalEntrySchema,
  projectSchema,
  projectToneSchema,
  sessionEntryOriginSchema,
  sessionEntrySchema,
  sessionSchema,
  sessionTitleSourceSchema,
  sidebarPreferenceSchema,
  themePreferenceSchema,
} from './engine.ts'
export type {
  Channel,
  ComposerChoice,
  DisplayPreferences,
  DisplayPreferencesChange,
  EngineArguments,
  EngineEvent,
  EngineEventName,
  EngineRequestName,
  EngineRequests,
  EngineResponse,
  EngineStatus,
  SidebarPreference,
  ThemePreference,
  JournalEntry,
  Project,
  Session,
  SessionEntry,
  SessionEntryOrigin,
  SessionTitleSource,
} from './engine.ts'
export {
  agentAvailabilitySchema,
  agentOfferRefusalSchema,
  agentOfferSchema,
  agentProviderSchema,
  agentUpdateSchema,
  bareModeSchema,
  configOptionSchema,
  installerToolSchema,
  resumeStateSchema,
  stopReasonSchema,
  toolCallStatusSchema,
} from './agents.ts'
export type {
  AgentAvailability,
  AgentOffer,
  AgentOfferRefusal,
  AgentProvider,
  AgentUpdate,
  BareModeState,
  ConfigOption,
  InstallerTool,
  ResumeState,
  StopReason,
  ToolCallStatus,
} from './agents.ts'
export {
  commandKindSchema,
  commandRunSchema,
  commandSchema,
  contextReachSchema,
  contextViewSchema,
  providedSchema,
  runStateSchema,
} from './tools.ts'
export type { Command, CommandKind, CommandRun, ContextView, Provided, RunState } from './tools.ts'
