/** Public surface of the Hemera domain and use cases. */

export {
  CLASSIFIER_POLICY_VERSION,
  classifierVerdictFromScores,
  localClassifierVerdict,
} from './domain/classifier.ts'

export {
  CLASSIFIER_CONTEXT_CHARACTERS,
  CLASSIFIER_ITEM_CHARACTERS,
  CLASSIFIER_MESSAGE_LIMIT,
  classifierHumanContext,
} from './domain/classifier-context.ts'
export type {
  FrozenSpecSection,
  HumanContext,
  HumanContextItem,
} from './domain/classifier-context.ts'
export type {
  ClassifierVerdict,
  LocalAction,
  LocalVerdict,
  ResolvedCommand,
} from './domain/classifier.ts'

export {
  FIRST_RANK,
  InvalidRankError,
  RankOrderError,
  compareRanks,
  isRank,
  rankBetween,
  ranksFor,
} from './domain/rank.ts'
export {
  InvalidProjectNameError,
  InvalidRepositoryPathError,
  MAIN_WORKSPACE,
  MAX_PROJECT_NAME_LENGTH,
  PROJECT_TONES,
  REPOSITORY_ICONS,
  ROOT_REPOSITORY,
  projectName,
  repositoryLocations,
  repositoryPath,
} from './domain/project.ts'
export type { Project, ProjectTone, RepositoryIcon, Workspace } from './domain/project.ts'
export {
  EmptyMessageError,
  EmptyTitleError,
  MAX_TITLE_LENGTH,
  NEW_SESSION_TITLE,
  NoActiveProjectError,
  NoAgentError,
  archivedSessions,
  currentSessions,
  isArchived,
  messageBody,
  sessionTitle,
  titleAfterMessage,
  titleFromMessage,
} from './domain/session.ts'
export type {
  AgentProvider,
  Mission,
  NativeState,
  Session,
  SessionEntry,
  SessionEntryKind,
  SessionEntryRole,
  SessionEntryOrigin,
  SessionTitleSource,
} from './domain/session.ts'
export {
  AGENT_PROVIDERS,
  MISSIONS,
  NATIVE_STATES,
  SESSION_ENTRY_KINDS,
  SESSION_ENTRY_ORIGINS,
} from './domain/session.ts'
export {
  READ_PAGE_BYTES,
  SEARCH_MATCH_LIMIT,
  SEARCH_SCAN_BYTES,
  SEARCH_SKIPS_LISTED,
  SPEC_PAGE_CHARACTERS,
  TOOL_LABELS,
  TOOL_NAMES,
  admitTool,
  hemeraToolNamed,
  offeredTools,
} from './domain/tools.ts'
export type {
  GuardDecision,
  SearchHit,
  SearchLimit,
  SearchResult,
  SearchSkip,
  ToolLabel,
  ToolMark,
  ToolName,
} from './domain/tools.ts'
export {
  COMMAND_SCOPES,
  COMMAND_TYPES,
  DuplicateCommandNameError,
  EmptyCommandLineError,
  EmptyCommandNameError,
  InvalidCommandFolderError,
  InvalidPortlessNameError,
  UnknownCommandScopeError,
  UnknownCommandTypeError,
  addressIn,
  commandFolder,
  commandLine,
  commandName,
  commandPlace,
  commandScope,
  commandType,
  joinsRunningRun,
  runsInMain,
  runsPortless,
  lineFor,
  portOf,
  portlessName,
  portlessNameFor,
} from './domain/commands.ts'
export type { Command, CommandScope, CommandType } from './domain/commands.ts'
export {
  AGENTS_FILE,
  CONTEXT_BASE,
  CONTEXT_REACHES,
  CONTEXT_SOURCES,
  DELIVERY_MARKER,
  contextUri,
  deliveryText,
  internalText,
} from './domain/context.ts'
export type { BaseReach, ContextReach, ContextSource } from './domain/context.ts'
export {
  InvalidVariableKeyError,
  InvalidWorkspaceNameError,
  LAUNCH_STATES,
  RECIPE_KINDS,
  STEP_KINDS,
  STEP_STATES,
  WORKSPACE_STATES,
  branchNameFor,
  defaultBranchPrefix,
  mergedEnvironment,
  nextPending,
  resumedSteps,
  slugify,
  stepsFor,
  variableKey,
  workspaceName,
  workspaceStateOf,
} from './domain/workspace.ts'
export type {
  LaunchState,
  RecipeKind,
  RecipeStep,
  StepKind,
  StepState,
  Variables,
  WorkspaceState,
  WorkspaceStep,
} from './domain/workspace.ts'
export {
  ATTEMPTS_BEFORE_YOURS,
  ATTEMPT_RESULTS,
  ATTEMPT_SCOPES,
  BUILD_PHASES,
  CHECK_VERDICTS,
  CHECK_WHEN,
  CHECK_WHERE,
  FILES_PLACEHOLDER,
  TASK_STATES,
  attemptResult,
  checkPlaces,
  checkProblem,
  dependantsOf,
  evaluateExpect,
  expandFiles,
  promotions,
  proposeChecks,
  readySet,
  satisfied,
  stateAfterAttempt,
  storyDone,
  taskLabels,
  tasksSettled,
} from './domain/build.ts'
export type {
  ActiveBuildPhase,
  AttemptResult,
  AttemptScope,
  BuildPhase,
  BuildTask,
  ChangedFile,
  CheckDraft,
  CheckExpect,
  CheckJudgement,
  CheckVerdict,
  CheckWhen,
  CheckWhere,
  ProjectCheck,
  Promotion,
  TaskState,
} from './domain/build.ts'
export {
  BASE_SECTIONS,
  DEFAULT_SPEC_PREFIX,
  DEFINE_PROTOCOL,
  InvalidAnswerError,
  InvalidSpecPrefixError,
  InvalidSpecTitleError,
  MAX_SLUG_LENGTH,
  PHASE_IDS,
  PHASE_STATES,
  SECTION_NAMES,
  SPEC_ACTORS,
  SPEC_STATUSES,
  SPEC_TYPES,
  SpecNotWritableError,
  StaleSectionError,
  TASK_EXECUTORS,
  TaskCycleError,
  answerTo,
  answerWords,
  contractOf,
  focusOf,
  nextPhaseStates,
  phaseExit,
  readyGate,
  sectionOwner,
  slugOf,
  specKey,
  specPrefix,
  specPrefixFrom,
  staleAfterWrite,
  takeOverRefusal,
  taskGraph,
  unbriefedEdit,
  writable,
} from './domain/spec.ts'
export type {
  AcceptanceCriterion,
  GateFailure,
  GraphProblem,
  MissionProtocol,
  PhaseId,
  PhaseState,
  ProtocolPhase,
  SectionName,
  Spec,
  SpecActor,
  SpecAnswer,
  SpecPhase,
  SpecQuestion,
  SpecQuestionOption,
  SpecRevision,
  SpecSection,
  SpecSnapshot,
  SpecStatus,
  SpecTask,
  SpecType,
  SpecWriter,
  TaskDependency,
  TaskExecutor,
  TaskSet,
  TaskStory,
  UserStory,
  WriteRefusal,
} from './domain/spec.ts'
export {
  DEFINE_MISSION_BRIEF,
  PHASE_BRIEFS,
  answersText,
  composeBrief,
  editsText,
  readerLine,
  renderSpecMarkdown,
} from './protocols/define/index.ts'
export type { BriefInput } from './protocols/define/index.ts'
export {
  BUILD_MISSION_BRIEF,
  BUILD_PHASE_BRIEFS,
  BUILD_PROTOCOL,
  composeBuildBrief,
} from './protocols/build/index.ts'
export type {
  BriefAttempt,
  BriefBlocker,
  BriefCheck,
  BriefFailure,
  BriefFile,
  BriefSnapshot,
  BriefTask,
  BuildBriefInput,
} from './protocols/build/index.ts'
